# 225150200111004_1 HAIKAL THORIQ ATHAYA_1
# 225150200111008_2 MUHAMMAD ARSYA ZAIN YASHIFA_2
# 225150201111001_3 JAVIER AAHMES REANSYAH_3
# 225150201111003_4 MUHAMMAD HERDI ADAM_4

# Start from the MLflow image
FROM ghcr.io/mlflow/mlflow:latest

# Install the PostgreSQL database driver AND the S3 driver (boto3)
RUN pip install psycopg2-binary boto3
