# 225150200111004_1 HAIKAL THORIQ ATHAYA_1
# 225150200111008_2 MUHAMMAD ARSYA ZAIN YASHIFA_2
# 225150201111001_3 JAVIER AAHMES REANSYAH_3
# 25150201111003_4 MUHAMMAD HERDI ADAM_4

name: Continuous Integration

on:
  push:
    branches: ["main"]
    paths:
      - "Scripts/**"
      - "App/**"
      - ".github/workflows/**"
      - "Data/**"
      - "Dockerfile"
      - "Makefile"
      - "requirements.txt"
  workflow_dispatch:

permissions: write-all

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Install Packages
        run: make install

      - name: Train Model
        run: make train

      - name: Create Evaluation Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval

      - name: Update Branch
        env:
          NAME: ${{ secrets.USER_NAME }}
          EMAIL: ${{ secrets.USER_EMAIL }}
        run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL
