# 225150200111004_1 HAIKAL THORIQ ATHAYA_1
# 225150200111008_2 MUHAMMAD ARSYA ZAIN YASHIFA_2
# 225150201111001_3 JAVIER AAHMES REANSYAH_3
# 25150201111003_4 MUHAMMAD HERDI ADAM_4

name: Pull Request Checks

on:
  pull_request:
    branches: ["main"]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packages
        run: make install
        
      - name: Format Code
        run: make format
